version: "3.9"

services:
  app:
    container_name: eventify-cont
    image: eventify
    tty: false                                                                    # false for `entrypoint` in Dockerfile
    stdin_open: false                                                             # false for `entrypoint` in Dockerfile
    env_file:
      - .env
    environment:
      # - MONGODB_CONNSTRING=mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_URL}   # local mongodb
      - MONGODB_CONNSTRING=mongodb+srv://${MONGO_URL}/${DB_NAME}                  # mongodb atlas
    volumes:
      - .:/app
      # - ./logs:/root/.npm/                                                      # troubleshooting logs
    ports:
      - ${PORT:-8000}:8000
    build:
      context: ./
      dockerfile: ./Dockerfile.web

  # LOCAL MONGODB
  # mongodb:
  #   image: mongo:latest
  #   env_file:
  #     - .env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
  #   ports:
  #     - 27017:27017

networks:
  default:
    driver: bridge
